### ISSUE TITLE
JWT Auth with Auth0

### ISSUE THREAD

**Issue by dafrie** [vochabular/admin-backend#14]
I had troubles finding a solution for our auth requirements. The way I have imagined, we will implement it this way:
![](https://user-images.githubusercontent.com/5886935/53291267-dcd18080-37b0-11e9-9944-f14d2c9fc7c9.png)

E.g., the backend does not have to provide any login/logout functionality, the only thing he does is getting the JWT from the header, checks the JWT signature for validity (usually via JWK) and (maybe at a later stage) extract the claims to do role based checks on resources.

The current setup with  https://django-graphql-jwt.domake.io/en/stable/ however I think does not provide this functionality, as it is intended to provide with your user store and login/logout mutation etc and I haven't found a way to configure the usage of auth0 this way.

I checked the following guides (which are for django-rest-framework, but should be similar to our needs with Graphene...):
- https://auth0.com/docs/quickstart/backend/django/01-authorization#setup-the-django-application
- https://auth0.com/blog/building-modern-applications-with-django-and-vuejs/
But somehow I didn't manage to work it out, probably because I am not really well versed with Django, even though it should be quite simple to add such kind of middleware to do the validation..

@worxli what do you think? What should we do? Do you have time to look into this or should we go the maybe more pragmatic way and handle all the auth stuff also in Django (vs. external in Auth0)?

**Comment by worxli** [comment]
I see auth0 is providing a RSA256 token. For that to work we need to install the cryptography package. After that, I still have an issue: the JWT library can't read the embedded certificate. Ill follow up on that.
