### ISSUE TITLE
DB Model Updates

### ISSUE THREAD

**Issue by worxli** [vochabular/admin-backend#19]
![DB_Model](https://user-images.githubusercontent.com/2504856/54951865-edf2e600-4f44-11e9-8201-0cd8880f78d3.png)

**Comment by worxli** [comment]
- Add audio source and example to `word_xxx`
- Add title, description and number to Chapter
- Add self-reference to Component
- Add comment-component reference
- Add author and written date to comment
- Add table media with type and url

**Comment by YanickSchraner** [comment]
WordGroups have a CH_Title and a DE_Title
