### ISSUE TITLE
DB model Updates

### ISSUE THREAD

**Issue by YanickSchraner** [vochabular/admin-backend#37]
New DB model updates required.
See DB model in the wiki.
List of what changed:
* [x] Title and number of the chapter must be unique
* [x] component has new locked_by (fk to User) and locked_timestamp
* [x] componentType has new self-reference
* [x] comment has new self-reference
* [x] comment now links to component and not text (n:1 and not n:m)
* [x] comment has now a "context", which is a Enum of one of the following: "Approver, ContentCreator, Translator, Illustrator" and can be null
* [x] Update graphene schema accordingly 
* [x] chapter has now titleCH and titleDE instead of a single title
* [x] New User table

Important: Don't add Event table by now. This will be handled in a separate issue.

**Comment by Sumanthini** [comment]
@YanickSchraner  Could you please tell me the fields for User table.

**Comment by Sumanthini** [comment]
@YanickSchraner  After creating the self-reference for Comment, there is a name clash error. 

ERRORS:
api.Comment.fk_comment: (fields.E303) Reverse query name for 'Comment.fk_comment' clashes with field name 'Comment.comment'.
        HINT: Rename field 'Comment.comment', or add/change a related_name argument to the definition for field 'Comment.fk_comment'.

Can I change the name of the field comment to comment_field?

**Comment by YanickSchraner** [comment]
Sure, you can find the diagram here: https://github.com/vochabular/admin-backend/wiki/Database-Model

For the user table the fields are:
* first name
* last name
* ui_language
* translator_languages

Language codes will be according to ISO 3166 two char codes: https://www.iso.org/iso-3166-country-codes.html.

**Comment by YanickSchraner** [comment]
> @YanickSchraner After creating the self-reference for Comment, there is a name clash error.
> 
> ERRORS:
> api.Comment.fk_comment: (fields.E303) Reverse query name for 'Comment.fk_comment' clashes with field name 'Comment.comment'.
> HINT: Rename field 'Comment.comment', or add/change a related_name argument to the definition for field 'Comment.fk_comment'.
> 
> Can I change the name of the field comment to comment_field?

Yes, feel free to change it. Maybe we could use text or message instead of comment_filed?
