### ISSUE TITLE
User profile query: Don't return error when not found, return null/empty array

### ISSUE THREAD

**Issue by dafrie** [vochabular/admin-backend#57]
If the user logs in for the first time right now, currently the user profile query by email will return
an 400 error since there is obviously no default profile. Can we either:

a) Return a "default" profile, i.e have a default profile assigned to each user on creation 
b) Return a "default" profile when not found
c) Not return anything (null, empty) but no error (so status 200) since this will pop up in the console which is a bit ugly and the default values will be set on the client.

I prefer a). what do you think?

**Comment by worxli** [comment]
Needs more information.
