### ISSUE TITLE
Enable filtering of comments

### ISSUE THREAD

**Issue by dafrie** [vochabular/admin-backend#64]
Ideally, we can have the following filtering:
- Whether they are parentComments: Eg: comments(filter: {parentComment: { is_null: true }}}
- Whether they are active or not
- By the context. Eg: comments(filter: { context: { eq: "Approver" }})
- By their associated chapters.
    E.g: comments(filter: { component :{ chapter : { eq: "1.1"} } })

**Comment by dafrie** [comment]
Ah: also, should be able to order at least by creation date

**Comment by worxli** [comment]
Use hasura.
