### ISSUE TITLE
Ordering of 1:n relation between Chapter <--> Components

### ISSUE THREAD

**Issue by dafrie** [vochabular/admin-backend#77]
I think this is currently missing in the ERD. We need to store the ordering of the components of each chapter. Not only upon insertion of a component, but each drag and drop of components will have to update the ordering, so it's not so straightforward. Mu :

- Int field with order in the component table. Then, create a trigger that increments all components of this chapter above and, if already exists, decrements all chapters below. See third example: https://medium.com/the-missing-bit/keeping-an-ordered-collection-in-postgresql-9da0348c4bbe
- Use a Django Extension: For example: https://pypi.org/project/django-ordered-model/ and handle it Django-side. The update mutation then obviously needs to be provided by Graphene.
- Use the "Jira" approach: See second answer: https://stackoverflow.com/questions/9536262/best-representation-of-an-ordered-list-in-a-database

@worxli @YanickSchraner what do you think? I guess the second one is simplest?

**Comment by YanickSchraner** [comment]
For wordGroup we have a word_ordering varchar field, that moves the ordering process to the frontend. We would also need ordering for words inside a word group.
In total those elements need ordering
- WordGroup
- Word
- component

I think the "Jira" approach is a bit of an overkill, we don't have that many elements to be ordered so the elements to be updated should still be quite small. If we would use the Jira approach we should hide it to the frontend. 
The pro for the first approach is, that we still can use Hasura for those entities which I think is preferable. 
I would either choose option 1 or 2.

**Comment by worxli** [comment]
I'd do it in the frontend. @dafrie what's the status here?

**Comment by dafrie** [comment]
The PR #80 implements the first approach and currently works, but need to check fo some bugs/edge cases first before closing.
