### ISSUE TITLE
Change "data" field of "component" to Postgres JSONB type

### ISSUE THREAD

**Issue by dafrie** [vochabular/admin-backend#81]
Django supports JSON field, which would be suitable for our component type specific field "data" in the component model, which holds the setting values of the component instances. Hasura also supports JSON fields nicely, so that would give us an improvement:

https://docs.djangoproject.com/en/2.2/ref/contrib/postgres/fields/

**Comment by dafrie** [comment]
But not sure how that plays out with local dev with sqlite?

**Comment by worxli** [comment]
We can run postgres with docker locally.
