### ISSUE TITLE
Create Character table

### ISSUE THREAD

**Issue by YanickSchraner** [vochabular/admin-backend#85]
For our dialogue component, we need a central place to store characters. For this purpose (and some future interesting features) we need a new table "Character".
FormalName and InfromalName should be unique and not null
Gender is an enum (Male, Female) 😱 and nullable
title is nullable
speaker is nullable
details see updated ERM

**Comment by dafrie** [comment]
Also a character should always be associated with a book. So my suggestion:
- Add fk to "book"
- FormalName and InformalName unique, but only per book
@YanickSchraner Correct me if i am wrong
