### ISSUE TITLE
Update wordGroup table

### ISSUE THREAD

**Issue by YanickSchraner** [vochabular/admin-backend#86]
The wordGroup table needs some updates:
The connection to the member table should be nullable
The connection to the chapter table should be nullable
Due to changes to the design wordGroup "title" must be translatable => see updated ERM

**Comment by worxli** [comment]
`The connection to the member table should be nullable`, that's not possible. That is a many to many relationship. What is the rational? @YanickSchraner

**Comment by YanickSchraner** [comment]
well this should be possible, as the primary key is on the member side and not the wordGroup side.
Currently, we first create an empty word group as it is way easier this way with the UI implementation and the different languages. So to make the change clear:
A word groud may have none, one or many members. A member must have exactly one word group.
